version: "3"
services:
  app:
    container_name: market-board-app
    restart: always
    env_file:
      - ./.env
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - my_data:/data/db

volumes:
  my_data: